import type { TournamentConfig } from "./types";
import { MATCHES } from "@/lib/matches";
import { KNOCKOUT_MATCHES, KNOCKOUT_ROUNDS } from "@/lib/knockoutMatches";

export const wc2026: TournamentConfig = {
  id: "wc2026",
  name: "FIFA World Cup 2026",
  shortName: "WC 2026",
  hosts: "USA / Canada / Mexico",
  year: 2026,
  emoji: "🏆",
  nations: [
    "Algeria",
    "Argentina",
    "Australia",
    "Austria",
    "Belgium",
    "Bosnia",
    "Brazil",
    "Cabo Verde",
    "Canada",
    "Colombia",
    "Croatia",
    "Czechia",
    "Curaçao",
    "DR Congo",
    "Ecuador",
    "Egypt",
    "England",
    "France",
    "Germany",
    "Ghana",
    "Haiti",
    "Iran",
    "Iraq",
    "Ivory Coast",
    "Japan",
    "Jordan",
    "Mexico",
    "Morocco",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Panama",
    "Paraguay",
    "Portugal",
    "Qatar",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "South Africa",
    "South Korea",
    "Spain",
    "Sweden",
    "Switzerland",
    "Tunisia",
    "Türkiye",
    "Uruguay",
    "USA",
    "Uzbekistan",
  ],
  groups: MATCHES,
  knockoutRounds: KNOCKOUT_ROUNDS,
  knockout: KNOCKOUT_MATCHES,
  finalsMatch: { home: "Spain", away: "Argentina" },
};
